name: wjpdealer
description: ""
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.5.0-143.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.4.3 # 网络请求
  shared_preferences: ^2.2.3 # 本地存储
  get: ^4.6.6 # 状态管理
  bruno: ^3.4.3
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
