name: wrdealer
description: "wanrun dealer"
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.5.0-131.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.3 # 网络请求
  flutter_screenutil: ^5.9.0 # 屏幕适配
  shared_preferences: ^2.2.3 # 本地存储
  flutter_swiper_view: ^1.1.8 # 轮播图
  flutter_staggered_grid_view: ^0.7.0 # 瀑布流
  get: ^4.6.6 # 状态管理
  tdesign_flutter: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
